import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link' 

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
      <div className="1st mx-7 my-8">
        <table cellSpacing={"20"} >
          <tbody>
            <tr>
              <td>
                <img  className='mr-5 w-52 'src="./angela yu.png" alt="" />
              </td>
              <td >
                <h1 className='text-3xl mb-4 font-serif   text-blue-300 cursor-pointer hover:text-blue-400 font-bold'>Angela Yu</h1>
                <h3 className='text-base mb-2 font-sans font-semibold '>Founder and CTO of <span>the App Brewery .</span></h3>
                <p className='mb-2'>I am an IOS and Web developer . I love coffee and brew my own beers.</p>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      <hr  className='border-dotted  border-blue-300  w-32 mx-auto border-t-8 my-8 cursor-pointer hover:border-gray-400'/>
      <div className="2nd  m-3">
        <h1 className='text-xl mb-2 font-serif text-blue-300 cursor-pointer hover:text-blue-400 font-bold'>Books and Teaching</h1>
        <ul className='list-disc mx-10 my-2'>
          <li className='list-disc'>The Complete IOS Development Bootcamp</li>
          <li>The Complete Web Development Bootcamp</li>
        </ul>
      </div>
      <hr  className='border-dotted  border-blue-300  w-32 mx-auto border-t-8 my-8 cursor-pointer hover:border-gray-400'/>
      <div className="3rd m-3">
        <h1 className='text-xl mb-2 text-blue-300 cursor-pointer hover:text-blue-400 font-serif font-bold'>Working Experience</h1>
        <table className='mx-6'>
          <thead>
          <tr cellSpacing='50'>
            <th>Dates</th>
            <th className='pr-14'>Work</th>
          </tr>
          </thead>
          <tbody>
          <tr>
            <td>2010-2012</td>
            <td className='pl-4'>Lead Developer in Tempo App</td>
          </tr>
          <tr>
            <td>2010</td>
            <td className='pl-4'>Researcher at the Institute of Cognitive Neuroscience</td>
          </tr>
          </tbody>
        </table>
      </div>
      <hr  className='border-dotted  border-blue-300  w-32 mx-auto border-t-8 my-8 cursor-pointer hover:border-gray-400'/>
      <div className="4th m-3">
        <h1 className='text-xl mb-2 text-blue-300 cursor-pointer hover:text-blue-400 font-serif font-bold'>Skills</h1>
        <table>
          <tbody>
          <tr>
            <td>
              <table  className='mx-6' cellspacing="5">
                <tbody>
              <tr>
                <td>IOS developer</td>
                <td>🌟🌟🌟🌟🌟</td>
              </tr>
              <tr>
                <td>Photography</td>
                <td>🌟🌟🌟</td>
              </tr>
                </tbody>
            </table></td>
            <td><table cellspacing="5">
              <tbody>
              <tr>
                <td>Web Development</td>
                <td>🌟🌟🌟🌟🌟</td>
              </tr>
              <tr>
                <td>Painting</td>
                <td>🌟🌟🌟🌟</td>
              </tr>
              </tbody>
            </table></td>
          </tr>
          </tbody>
        </table>
      </div>
      <hr  className='border-dotted  border-blue-300  w-32 mx-auto border-t-8 my-8 cursor-pointer hover:border-gray-400'/>
      <div className="5th bg-blue-300 text-center space-x-14 py-5">
        <span className='font-mono font-bold text-lg text-blue-400 hover:text-gray-500 cursor-pointer' ><Link href={"/hobies"} >My Hobies</Link></span> <span className='font-mono font-bold text-lg text-blue-400 hover:text-gray-500 cursor-pointer' > <Link href={"/contactUs"}> Contact us</Link></span>
      </div>
      </main>

   
    </div>
  )
}
